fix(app/tray): Avoid panic when failing to create tray icon
When the tray icon fails to construct (for example, on a DE that
doesn't support that funcionality), the unwrap on line 73 causes
a panic.
Even though it is not severe, since the app works anyway, it's
better to avoid the panic, and print an error message instead.

Original output:
```
thread 'tokio-rt-worker' (35925) panicked at src/app/tray/imp.rs:73:18:
Failed to create tray icon: Watcher(ServiceUnknown("The name is not activatable"))
```

New output:
```
Failed to create tray icon: failed to register to the StatusNotifierWatcher:
        org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```